//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class Candidates_Skills
    {
        public long Id { get; set; }
        public Nullable<long> CandidateId { get; set; }
        public Nullable<long> SkillId { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
